name = "LeanBzip2"
version = "0.1.0"

[[lean_lib]]
name = "Bzip2"

[[lean_exe]]
name = "bzip2"
root = "Bzip2"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "huffman"
git = "https://github.com/AnirudhG07/LeanHuffmanCoding.git"
rev = "783017d2dc1e2cbc8d4d5ff9f533a74e2a7b9125"
