name = "LeanBzip2"
version = "0.1.0"

[[lean_lib]]
name = "Bzip2"

[[lean_lib]]
name = "tests"

[[lean_exe]]
name = "bzip2"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "huffman"
git = "https://github.com/AnirudhG07/LeanHuffmanCoding.git"
rev = "82acb4cfbe7deffbba3c110b188286a527429b63"
